spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.254.232:8848
        ephemeral: true # 配置实例是否临时 AP/CP 在最早Nacos版本是被写死在NacosServiceRegistry中只能修改源码
        namespace: dev
  main:
    allow-bean-definition-overriding: true
server:
  port: 8888
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  PoolMaxThreads: 100
  MaxAutoRetries: 0
  eager-load.enabled: true
logging:
  level:
    com.xz.consumer: debug
feign:
  client:
    config:
      nacos-producer:
        loggerLevel: FULL
        connectTimeout: 10000
        readTimeout: 10000
